#!/usr/bin/env bash

if ! cargo fmt --check ; then
    echo "pre-commit: rustfmt failure, commit aborted"
    exit 1
fi

if ! cargo run --bin kra-lint-test --quiet ; then
    echo "pre-commit: test failure, commit aborted"
    exit 1
fi

exit 0
