[workspace]
resolver = "2"
members = [
    "crates/kra-lint-cli",
    "crates/kra-lint-impl",
    "crates/kra-lint-test",
    "crates/kra-parser",
    "crates/ziparchive-ext",
    "crates/camino-ext",
]
