[workspace]
resolver = "2"
members = [
    "crates/kra-lint-cli",
    "crates/kra-lint-impl",
    "crates/kra-lint-test",
    "crates/kra-parser",

    "crates-ext/camino-ext",
    "crates-ext/std-ext",
    "crates-ext/ziparchive-ext",
]
