[package]
name = "ziparchive-ext"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
