[package]
name = "kra-lint-impl"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.70"

[dependencies]
kra-parser = { path = "../kra-parser/" }

camino-ext = { path = "../../crates-ext/camino-ext/" }
ziparchive-ext = { path = "../../crates-ext/ziparchive-ext/" }

camino = { version = "1.1.4", features = ["serde1"] }
derive_more = { version = "0.99.17", default-features = false, features = ["into_iterator", "display", "error", "from"] }
itertools = "0.10.5"
regex = "1.8.1"
strum = { version = "0.24.1", features = ["derive"] }
svg = "0.13.1"
unicode-width = "0.1.10"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }

base16ct = { version = "0.2.0", features = ["alloc"] }
sha2 = "0.10.6"

serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
serde_json = "1.0.96"
deser-hjson = "1.1.1"
ron = "0.8.0"
serde_yaml = "0.9.21"
serde-pickle = "1.1.1"
