[package]
name = "kra-lint-impl"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.70"

[dependencies]
# kra-lint library crates
kra-parser = { workspace = true }

# kra-lint private extension crates
camino-ext     = { workspace = true }
std-ext        = { workspace = true }
ziparchive-ext = { workspace = true }

# common workspace dependencies
camino      = { workspace = true }
derive_more = { workspace = true }
itertools   = { workspace = true }
serde       = { workspace = true }
strum       = { workspace = true }
zip         = { workspace = true }

# private dependencies - general
regex         = { version = "1.8.1"  }
svg           = { version = "0.13.1" }
unicode-width = { version = "0.1.10" }
unix_mode     = { version = "0.1.3"  }

# private dependencies - hashing
base16ct = { version = "0.2.0", features = ["alloc"] }
sha2     = { version = "0.10.6" }

# private dependencies - serde
toml         = { version = "0.7.3"  }
serde_json   = { version = "1.0.96" }
deser-hjson  = { version = "1.1.1"  }
ron          = { version = "0.8.0"  }
serde_yaml   = { version = "0.9.21" }
serde-pickle = { version = "1.1.1"  }
