[package]
name = "kra-lint-impl"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
kra-parser = { path = "../kra-parser/" }

camino = { version = "1.1.4", features = ["serde1"] }
regex = "1.8.1"

serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
deser-hjson = "1.1.1"
ron = "0.8.0"
serde_yaml = "0.9.21"
