[package]
name = "ziparchive-ext"
version = "0.1.0"
authors = ["Nagy Tibor <xnagytibor@protonmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.70"

[dependencies]
# common workspace dependencies
zip = { workspace = true }
